import { CosechaItem, PrecioMercado, AlmacenInsumos, Transportista, Agremiacion, NoticiaAgraria, EmpleoItem } from '@/types/agro';

export const COSECHAS_DATA: CosechaItem[] = [
  // ==================== SECTOR AGRÍCOLA ====================
  {
    id: 'cos-001',
    titulo: 'Aguacate Hass Calibre 14-22 de Exportación',
    sector: 'agricola',
    categoria: 'Frutas Frescas',
    variedad: 'Aguacate Hass',
    cantidadDisponible: 28,
    unidad: 'Toneladas',
    precioUnitario: 5200,
    moneda: 'COP',
    departamento: 'Antioquia',
    municipio: 'Sonsón',
    vereda: 'La Soledad',
    coordenadas: [-75.3106, 5.7114],
    productor: {
      nombre: 'Don Hernando Gómez',
      finca: 'Finca La Esmeralda',
      verificadoKYC: true,
      calificacion: 4.9,
      telefono: '+573114567890',
      whatsapp: '573114567890',
      experienciaAnos: 14
    },
    fechaCosechaEstimada: 'Cosecha en curso (Disponible 15 días)',
    fechaPublicacion: '2026-09-08',
    imagenes: ['https://images.unsplash.com/photo-1523049673857-eb18f1d7b578?auto=format&fit=crop&w=900&q=80'],
    descripcion: 'Lote con certificación ICA y GlobalGAP. Materia seca > 24%. Listo para cargue en finca.',
    certificaciones: ['GlobalGAP', 'BPA ICA', 'Predio Exportador']
  },
  {
    id: 'cos-002',
    titulo: 'Café Especial Castillo - Taza Limpia 86+',
    sector: 'agricola',
    categoria: 'Cafés Especiales',
    variedad: 'Castillo Lavado Suave',
    cantidadDisponible: 65,
    unidad: 'Cargas',
    precioUnitario: 2450000,
    moneda: 'COP',
    departamento: 'Huila',
    municipio: 'Pitalito',
    vereda: 'Criollo',
    coordenadas: [-76.0506, 1.8542],
    productor: {
      nombre: 'Asociación Cafetera El Mirador',
      finca: 'Hacienda El Cafetal',
      verificadoKYC: true,
      calificacion: 5.0,
      telefono: '+573138901234',
      whatsapp: '573138901234',
      experienciaAnos: 22
    },
    fechaCosechaEstimada: 'Octubre 2026',
    fechaPublicacion: '2026-09-09',
    imagenes: ['https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?auto=format&fit=crop&w=900&q=80'],
    descripcion: 'Café a 1.750 msnm. Notas a panela, frutos rojos y acidez cítrica brillante.',
    certificaciones: ['Denominación Huila', 'FairTrade', 'Rainforest Alliance']
  },
  {
    id: 'cos-005',
    titulo: 'Plátano Hartón Verde de Primera Selección',
    sector: 'agricola',
    categoria: 'Musáceas',
    variedad: 'Plátano Dominico Hartón',
    cantidadDisponible: 35,
    unidad: 'Toneladas',
    precioUnitario: 3100,
    moneda: 'COP',
    departamento: 'Quindío',
    municipio: 'Armenia',
    vereda: 'El Caimo',
    coordenadas: [-75.6811, 4.5339],
    productor: {
      nombre: 'Cooperativa Agroplátano del Eje',
      finca: 'Finca La Ceiba',
      verificadoKYC: true,
      calificacion: 4.7,
      telefono: '+573123344556',
      whatsapp: '573123344556',
      experienciaAnos: 9
    },
    fechaCosechaEstimada: 'Disponible todo el mes',
    fechaPublicacion: '2026-09-08',
    imagenes: ['https://images.unsplash.com/photo-1571771894821-ce9b6c11b08e?auto=format&fit=crop&w=900&q=80'],
    descripcion: 'Racimos de alto peso y longitud superior a 25 cm, ideal para supermercados y plantas de patacón.',
    certificaciones: ['BPA ICA']
  },
  {
    id: 'cos-006',
    titulo: 'Papa Pastusa y R-12 Lavada de Páramo',
    sector: 'agricola',
    categoria: 'Tubérculos',
    variedad: 'Pastusa Suprema / Diacol Capiro',
    cantidadDisponible: 600,
    unidad: 'Bultos',
    precioUnitario: 85000,
    moneda: 'COP',
    departamento: 'Cundinamarca',
    municipio: 'Villapinzón',
    vereda: 'Chasquez',
    coordenadas: [-73.5936, 5.2153],
    productor: {
      nombre: 'Cultivos Don Álvaro Pinzón',
      finca: 'El Robledal',
      verificadoKYC: true,
      calificacion: 4.85,
      telefono: '+573182233445',
      whatsapp: '573182233445',
      experienciaAnos: 26
    },
    fechaCosechaEstimada: 'Inmediata',
    fechaPublicacion: '2026-09-09',
    imagenes: ['https://images.unsplash.com/photo-1518977676601-b53f82aba655?auto=format&fit=crop&w=900&q=80'],
    descripcion: 'Papa gruesa clasificada en bodega sobre asfalto, empacada en costales limpios de 50 kg.',
    certificaciones: ['Registro ICA']
  },
  {
    id: 'cos-009',
    titulo: 'Cacao Fino y de Aroma Clon CCN-51 y TCH',
    sector: 'agricola',
    categoria: 'Cacao & Chocolatería',
    variedad: 'CCN-51 / Fedecacao',
    cantidadDisponible: 12,
    unidad: 'Toneladas',
    precioUnitario: 17800,
    moneda: 'COP',
    departamento: 'Santander',
    municipio: 'San Vicente de Chucurí',
    vereda: 'Cantagallos',
    coordenadas: [-73.4147, 6.8814],
    productor: {
      nombre: 'Asocacao Yariguíes',
      finca: 'El Paraíso Cacaotero',
      verificadoKYC: true,
      calificacion: 4.95,
      telefono: '+573165544332',
      whatsapp: '573165544332',
      experienciaAnos: 19
    },
    fechaCosechaEstimada: 'Fermentado al 80% y seco al 7%',
    fechaPublicacion: '2026-09-10',
    imagenes: ['https://images.unsplash.com/photo-1587132137056-bfbf0166836e?auto=format&fit=crop&w=900&q=80'],
    descripcion: 'Grano fermentado en cajones de laurel por 6 días, secado solar. Notas afrutadas.',
    certificaciones: ['Denominación Santander', 'UTZ']
  },
  {
    id: 'cos-010',
    titulo: 'Mango de Azúcar Gourmet del Magdalena',
    sector: 'agricola',
    categoria: 'Frutas Tropicales',
    variedad: 'Mango de Azúcar',
    cantidadDisponible: 40,
    unidad: 'Toneladas',
    precioUnitario: 2800,
    moneda: 'COP',
    departamento: 'Magdalena',
    municipio: 'Ciénaga',
    vereda: 'Cordobita',
    coordenadas: [-74.2464, 11.0069],
    productor: {
      nombre: 'Frutícola del Caribe',
      finca: 'Hacienda La Frutera',
      verificadoKYC: true,
      calificacion: 4.8,
      telefono: '+573012233445',
      whatsapp: '573012233445',
      experienciaAnos: 15
    },
    fechaCosechaEstimada: 'Disponible 20 días',
    fechaPublicacion: '2026-09-10',
    imagenes: ['https://images.unsplash.com/photo-1553279768-865429fa0078?auto=format&fit=crop&w=900&q=80'],
    descripcion: 'Brix > 15°, libre de antracnosis con tratamiento hidrotérmico para despacho nacional.',
    certificaciones: ['BPA ICA Exportación']
  },
  {
    id: 'cos-015',
    titulo: 'Uchuva de Exportación sin Cáliz y con Capacho',
    sector: 'agricola',
    categoria: 'Frutas Exóticas',
    variedad: 'Uchuva Ecovariedad Colombia',
    cantidadDisponible: 8,
    unidad: 'Toneladas',
    precioUnitario: 7500,
    moneda: 'COP',
    departamento: 'Boyacá',
    municipio: 'Ventaquemada',
    vereda: 'Montenegro',
    coordenadas: [-73.5244, 5.3725],
    productor: {
      nombre: 'Asociación de Uchuveros de Boyacá',
      finca: 'Finca El Sol Naciente',
      verificadoKYC: true,
      calificacion: 4.9,
      telefono: '+573154433221',
      whatsapp: '573154433221',
      experienciaAnos: 12
    },
    fechaCosechaEstimada: 'Cosechas semanales programadas',
    fechaPublicacion: '2026-09-10',
    imagenes: ['https://images.unsplash.com/photo-1509358271058-acd22cc93898?auto=format&fit=crop&w=900&q=80'],
    descripcion: 'Uchuva dorada clasificada por calibre A y B, empacada en canastillas plásticas ventiladas.',
    certificaciones: ['GlobalGAP', 'BPA ICA']
  },
  {
    id: 'cos-016',
    titulo: 'Cebolla Junca Larga de Aquitania',
    sector: 'agricola',
    categoria: 'Hortalizas',
    variedad: 'Junca Gigante',
    cantidadDisponible: 1200,
    unidad: 'Bultos',
    precioUnitario: 48000,
    moneda: 'COP',
    departamento: 'Boyacá',
    municipio: 'Aquitania',
    vereda: 'Mombita',
    coordenadas: [-72.8912, 5.5211],
    productor: {
      nombre: 'Agropecuaria Lago Verde',
      finca: 'El Juncal',
      verificadoKYC: true,
      calificacion: 4.75,
      telefono: '+573189900112',
      whatsapp: '573189900112',
      experienciaAnos: 20
    },
    fechaCosechaEstimada: 'Diario permanente',
    fechaPublicacion: '2026-09-09',
    imagenes: ['https://images.unsplash.com/photo-1618512496248-a07fe83aa8cb?auto=format&fit=crop&w=900&q=80'],
    descripcion: 'Tallo grueso y blanco, lavada con agua dulce y amarrada en rollos de 40 kg.',
    certificaciones: ['Registro ICA']
  },
  {
    id: 'cos-017',
    titulo: 'Arroz Paddy Verde Variedad Fedearroz 67',
    sector: 'agricola',
    categoria: 'Cereales & Granos',
    variedad: 'Fedearroz 67 Riego',
    cantidadDisponible: 150,
    unidad: 'Toneladas',
    precioUnitario: 1850,
    moneda: 'COP',
    departamento: 'Tolima',
    municipio: 'Espinal',
    vereda: 'Chicoral',
    coordenadas: [-74.8839, 4.1492],
    productor: {
      nombre: 'Hacienda Arrocera San Isidro',
      finca: 'El Arrozal Tolimense',
      verificadoKYC: true,
      calificacion: 4.88,
      telefono: '+573176655443',
      whatsapp: '573176655443',
      experienciaAnos: 30
    },
    fechaCosechaEstimada: 'Cosecha mecanizada en 8 días',
    fechaPublicacion: '2026-09-10',
    imagenes: ['https://images.unsplash.com/photo-1586201375761-83865001e31c?auto=format&fit=crop&w=900&q=80'],
    descripcion: 'Arroz de alta masa molinera con humedad al 22% listo para entrega en molino.',
    certificaciones: ['FEDEARROZ', 'Distrito de Riego USOCOELLO']
  },
  {
    id: 'cos-018',
    titulo: 'Limón Tahití Verde Esmeralda de Exportación',
    sector: 'agricola',
    categoria: 'Cítricos',
    variedad: 'Lima Ácida Tahití',
    cantidadDisponible: 30,
    unidad: 'Toneladas',
    precioUnitario: 3800,
    moneda: 'COP',
    departamento: 'Santander',
    municipio: 'Lebrija',
    vereda: 'El Centenario',
    coordenadas: [-73.2183, 7.1147],
    productor: {
      nombre: 'Cítricos del Chicamocha',
      finca: 'La Limonera Real',
      verificadoKYC: true,
      calificacion: 4.92,
      telefono: '+573145566778',
      whatsapp: '573145566778',
      experienciaAnos: 14
    },
    fechaCosechaEstimada: 'Disponible todo el año',
    fechaPublicacion: '2026-09-08',
    imagenes: ['https://images.unsplash.com/photo-1533089860892-a7c6f0a88666?auto=format&fit=crop&w=900&q=80'],
    descripcion: 'Limón jugoso sin semilla, porcentaje de jugo superior al 45%, piel verde intensa.',
    certificaciones: ['GlobalGAP', 'Predio Exportador ICA']
  },
  {
    id: 'cos-019',
    titulo: 'Fríjol Cargamanto Rojo y Blanco de Origen',
    sector: 'agricola',
    categoria: 'Legumbres',
    variedad: 'Cargamanto Rojo Valle de Aburrá',
    cantidadDisponible: 200,
    unidad: 'Bultos',
    precioUnitario: 320000,
    moneda: 'COP',
    departamento: 'Antioquia',
    municipio: 'Urrao',
    vereda: 'Penderisco',
    coordenadas: [-76.1342, 6.3164],
    productor: {
      nombre: 'Cooperativa Agrícola del Penderisco',
      finca: 'El Semillero',
      verificadoKYC: true,
      calificacion: 4.9,
      telefono: '+573128899776',
      whatsapp: '573128899776',
      experienciaAnos: 18
    },
    fechaCosechaEstimada: 'Grano seco seleccionado',
    fechaPublicacion: '2026-09-09',
    imagenes: ['https://images.unsplash.com/photo-1551462147-ff29053bfc14?auto=format&fit=crop&w=900&q=80'],
    descripcion: 'Grano grueso y parejo, cosechado tradicionalmente en espaldera.',
    certificaciones: ['BPA ICA']
  },
  {
    id: 'cos-020',
    titulo: 'Panela Pulverizada Orgánica y en Bloque Tradicional',
    sector: 'agricola',
    categoria: 'Agroindustria Panelera',
    variedad: 'Caña Panelera RD-7511',
    cantidadDisponible: 15,
    unidad: 'Toneladas',
    precioUnitario: 4600,
    moneda: 'COP',
    departamento: 'Cundinamarca',
    municipio: 'Villeta',
    vereda: 'Bagazal',
    coordenadas: [-74.4744, 5.0119],
    productor: {
      nombre: 'Trapiche La Miel Dorada',
      finca: 'Hacienda El Trapiche',
      verificadoKYC: true,
      calificacion: 5.0,
      telefono: '+573104433221',
      whatsapp: '573104433221',
      experienciaAnos: 35
    },
    fechaCosechaEstimada: 'Molienda semanal continua',
    fechaPublicacion: '2026-09-10',
    imagenes: ['https://images.unsplash.com/photo-1587132137056-bfbf0166836e?auto=format&fit=crop&w=900&q=80'],
    descripcion: 'Panela 100% natural libre de sulfito y clarificantes químicos. Registro sanitario INVIMA.',
    certificaciones: ['INVIMA', 'Certificado Orgánico Ecocert', 'FEDEPANELA']
  },

  // ==================== SECTOR GANADERO ====================
  {
    id: 'cos-003',
    titulo: 'Lote de Novillos de Ceba Brahman Blanco Comercial',
    sector: 'ganadero',
    categoria: 'Bovinos de Ceba',
    variedad: 'Brahman Blanco / F1',
    cantidadDisponible: 80,
    unidad: 'Cabezas',
    precioUnitario: 9400,
    moneda: 'COP',
    departamento: 'Córdoba',
    municipio: 'Montería',
    vereda: 'Km 15 Vía Planeta Rica',
    coordenadas: [-75.8814, 8.7479],
    productor: {
      nombre: 'Ganadería Santa Catalina (Carlos Restrepo)',
      finca: 'Hato San Jerónimo',
      verificadoKYC: true,
      calificacion: 4.8,
      telefono: '+573007654321',
      whatsapp: '573007654321',
      experienciaAnos: 18
    },
    fechaCosechaEstimada: 'Disponible pesaje inmediato en báscula',
    fechaPublicacion: '2026-09-07',
    imagenes: ['https://images.unsplash.com/photo-1546445317-29f4545e9d53?auto=format&fit=crop&w=900&q=80'],
    descripcion: 'Novillos promedio 460 kg con plan sanitario completo, libres de brucelosis y aftosa con guía ICA.',
    certificaciones: ['Hato Libre de Brucelosis ICA', 'Registro Ganadero']
  },
  {
    id: 'cos-008',
    titulo: 'Vacas Doble Propósito Simmental x Gyr Lecheras',
    sector: 'ganadero',
    categoria: 'Lechería y Cría',
    variedad: 'Simmgyr / Girolando',
    cantidadDisponible: 30,
    unidad: 'Cabezas',
    precioUnitario: 4800000,
    moneda: 'COP',
    departamento: 'Santander',
    municipio: 'Socorro',
    vereda: 'Barirí',
    coordenadas: [-73.2625, 6.4678],
    productor: {
      nombre: 'Criadero & Finca El Remanso',
      finca: 'Hacienda El Remanso',
      verificadoKYC: true,
      calificacion: 4.9,
      telefono: '+573142211990',
      whatsapp: '573142211990',
      experienciaAnos: 20
    },
    fechaCosechaEstimada: 'Disponible con genealogía',
    fechaPublicacion: '2026-09-06',
    imagenes: ['https://images.unsplash.com/photo-1527153857715-3908f2ae5e81?auto=format&fit=crop&w=900&q=80'],
    descripcion: 'Hembras de primer y segundo parto con producciones comprobadas de 18 Lts/día. Inseminación con toros alemanes.',
    certificaciones: ['ASOSIMMENTAL', 'Hato Libre ICA']
  },
  {
    id: 'cos-011',
    titulo: 'Terneros de Levante Brahman Rojo Puro Registrados',
    sector: 'ganadero',
    categoria: 'Reproductores & Cría',
    variedad: 'Brahman Rojo ASOBICEBÚ',
    cantidadDisponible: 25,
    unidad: 'Cabezas',
    precioUnitario: 6200000,
    moneda: 'COP',
    departamento: 'Meta',
    municipio: 'Puerto López',
    vereda: 'La Venturosa',
    coordenadas: [-72.9567, 4.0847],
    productor: {
      nombre: 'Ganadería Llanos Orientales (Dr. Andrés Arango)',
      finca: 'Hacienda El Rodeo',
      verificadoKYC: true,
      calificacion: 5.0,
      telefono: '+573108899776',
      whatsapp: '573108899776',
      experienciaAnos: 24
    },
    fechaCosechaEstimada: 'Destetos de 8 meses (240 Kg promedio)',
    fechaPublicacion: '2026-09-09',
    imagenes: ['https://images.unsplash.com/photo-1570042225831-d98fa7577f1e?auto=format&fit=crop&w=900&q=80'],
    descripcion: 'Hijos de toros campeones en Agroexpo, mansedumbre y excelente conformación cárnica.',
    certificaciones: ['Registro Genealógico ASOCEBU']
  },
  {
    id: 'cos-012',
    titulo: 'Búfalas Murrah y Mediterráneo Productoras Leche A2',
    sector: 'ganadero',
    categoria: 'Bufalinos',
    variedad: 'Murrah / Mediterráneo',
    cantidadDisponible: 20,
    unidad: 'Cabezas',
    precioUnitario: 5300000,
    moneda: 'COP',
    departamento: 'Antioquia',
    municipio: 'Caucasia (Bajo Cauca)',
    vereda: 'El Silencio',
    coordenadas: [-75.1950, 7.9869],
    productor: {
      nombre: 'Bufalera del San Jorge',
      finca: 'Finca La Búfala de Oro',
      verificadoKYC: true,
      calificacion: 4.88,
      telefono: '+573153322110',
      whatsapp: '573153322110',
      experienciaAnos: 16
    },
    fechaCosechaEstimada: 'Primer tercio de lactancia comprobada',
    fechaPublicacion: '2026-09-10',
    imagenes: ['https://images.unsplash.com/photo-1500595046743-cd271d694d30?auto=format&fit=crop&w=900&q=80'],
    descripcion: 'Búfalas preñadas con 8.5% de grasa láctea ideal para quesería gourmet.',
    certificaciones: ['ASOBÚFALOS', 'Predio Libre Brucelosis']
  },
  {
    id: 'cos-021',
    titulo: 'Lote de Ovejas y Corderos Dorper x Katahdin de Ceba',
    sector: 'ganadero',
    categoria: 'Ovinos & Caprinos',
    variedad: 'Dorper / Katahdin',
    cantidadDisponible: 50,
    unidad: 'Cabezas',
    precioUnitario: 450000,
    moneda: 'COP',
    departamento: 'Cesar',
    municipio: 'Valledupar',
    vereda: 'Río Seco',
    coordenadas: [-73.2532, 10.4631],
    productor: {
      nombre: 'Ovinos del Valle del Cacique Upar',
      finca: 'El Redil Guajiro',
      verificadoKYC: true,
      calificacion: 4.82,
      telefono: '+573117766554',
      whatsapp: '573117766554',
      experienciaAnos: 11
    },
    fechaCosechaEstimada: 'Corderos de 35 kg listos para beneficio',
    fechaPublicacion: '2026-09-08',
    imagenes: ['https://images.unsplash.com/photo-1484557052118-f32bd25b45b5?auto=format&fit=crop&w=900&q=80'],
    descripcion: 'Excelente conformación de pierna y lomo, alimentados con pastoreo intensivo y guácimo.',
    certificaciones: ['ASOOVINOS', 'Registro ICA']
  },
  {
    id: 'cos-022',
    titulo: 'Novillas Holstein Puras Registradas para Lechería',
    sector: 'ganadero',
    categoria: 'Lechería Especializada',
    variedad: 'Holstein Canadiense',
    cantidadDisponible: 18,
    unidad: 'Cabezas',
    precioUnitario: 7800000,
    moneda: 'COP',
    departamento: 'Nariño',
    municipio: 'Ipiales / Guachucal',
    vereda: 'San José',
    coordenadas: [-77.6444, 0.8286],
    productor: {
      nombre: 'Hacienda Lechera Los Volcanes',
      finca: 'El Prado del Sur',
      verificadoKYC: true,
      calificacion: 4.96,
      telefono: '+573205544332',
      whatsapp: '573205544332',
      experienciaAnos: 28
    },
    fechaCosechaEstimada: 'Preñeces confirmadas de 6 meses',
    fechaPublicacion: '2026-09-09',
    imagenes: ['https://images.unsplash.com/photo-1546445317-29f4545e9d53?auto=format&fit=crop&w=900&q=80'],
    descripcion: 'Madres con récord superior a 8.500 kg de leche por lactancia. Inseminación sexada.',
    certificaciones: ['ASOHOLSTEIN', 'Hato Libre Tuberculosis e ICA']
  },

  // ==================== SECTOR ACUÍCOLA ====================
  {
    id: 'cos-004',
    titulo: 'Tilapia Roja Entera Eviscerada Fresca / Congelada',
    sector: 'acuicola',
    categoria: 'Piscicultura Comercial',
    variedad: 'Tilapia Roja (Oreochromis)',
    cantidadDisponible: 18,
    unidad: 'Toneladas',
    precioUnitario: 14800,
    moneda: 'COP',
    departamento: 'Meta',
    municipio: 'Villavicencio',
    vereda: 'Apiay',
    coordenadas: [-73.5511, 4.1420],
    productor: {
      nombre: 'Piscícola Los Llanos (Ing. Diego Moreno)',
      finca: 'Estación Piscícola El Alcaraván',
      verificadoKYC: true,
      calificacion: 4.95,
      telefono: '+573159988776',
      whatsapp: '573159988776',
      experienciaAnos: 11
    },
    fechaCosechaEstimada: 'Saca semanal programada (Viernes)',
    fechaPublicacion: '2026-09-10',
    imagenes: ['https://images.unsplash.com/photo-1534043464124-3be32fe000c9?auto=format&fit=crop&w=900&q=80'],
    descripcion: 'Tilapia de 450-550 grs criada en jaulones flotantes con aguas puras de piedemonte.',
    certificaciones: ['AUNAP', 'Registro INVIMA', 'Buenas Prácticas Acuícolas']
  },
  {
    id: 'cos-007',
    titulo: 'Trucha Arcoíris de Agua Fría de Alta Montaña',
    sector: 'acuicola',
    categoria: 'Piscicultura Fría',
    variedad: 'Oncorhynchus mykiss',
    cantidadDisponible: 8,
    unidad: 'Toneladas',
    precioUnitario: 18900,
    moneda: 'COP',
    departamento: 'Boyacá',
    municipio: 'Aquitania (Lago de Tota)',
    vereda: 'Pérez',
    coordenadas: [-72.8872, 5.5194],
    productor: {
      nombre: 'Acuícola Lago Sagrado',
      finca: 'Estación Tota Truchas',
      verificadoKYC: true,
      calificacion: 4.9,
      telefono: '+573105556677',
      whatsapp: '573105556677',
      experienciaAnos: 15
    },
    fechaCosechaEstimada: 'Semanal permanente',
    fechaPublicacion: '2026-09-10',
    imagenes: ['https://images.unsplash.com/photo-1544551763-46a013bb70d5?auto=format&fit=crop&w=900&q=80'],
    descripcion: 'Trucha asalmonada y blanca de 350 grs criada a 3.015 msnm.',
    certificaciones: ['INVIMA', 'AUNAP']
  },
  {
    id: 'cos-013',
    titulo: 'Camarón Blanco Marino de Cultivo IQF',
    sector: 'acuicola',
    categoria: 'Camaronicultura',
    variedad: 'Litopenaeus vannamei',
    cantidadDisponible: 15,
    unidad: 'Toneladas',
    precioUnitario: 26000,
    moneda: 'COP',
    departamento: 'Bolívar',
    municipio: 'Cartagena / Bayunca',
    vereda: 'Pontezuela',
    coordenadas: [-75.4339, 10.4856],
    productor: {
      nombre: 'Acuícola del Caribe S.A.S.',
      finca: 'Camaronera San José',
      verificadoKYC: true,
      calificacion: 4.92,
      telefono: '+573004455667',
      whatsapp: '573004455667',
      experienciaAnos: 13
    },
    fechaCosechaEstimada: 'Cosecha mensual programada',
    fechaPublicacion: '2026-09-09',
    imagenes: ['https://images.unsplash.com/photo-1565680018434-b513d5e5fd47?auto=format&fit=crop&w=900&q=80'],
    descripcion: 'Talla 30-40 unidades por libra, congelado individual rápido en planta con agua marina.',
    certificaciones: ['HACCP', 'BAP 4 Estrellas', 'INVIMA']
  },
  {
    id: 'cos-014',
    titulo: 'Cachama Blanca y Bocachico de Represa de Betania',
    sector: 'acuicola',
    categoria: 'Peces Nativos',
    variedad: 'Piaractus brachypomus',
    cantidadDisponible: 20,
    unidad: 'Toneladas',
    precioUnitario: 12500,
    moneda: 'COP',
    departamento: 'Huila',
    municipio: 'Betania (Represa de Betania)',
    vereda: 'El Guásimo',
    coordenadas: [-75.4383, 2.7094],
    productor: {
      nombre: 'Piscícola Betania Fish',
      finca: 'Embalse Betania Sector 4',
      verificadoKYC: true,
      calificacion: 4.8,
      telefono: '+573139988112',
      whatsapp: '573139988112',
      experienciaAnos: 17
    },
    fechaCosechaEstimada: 'Quincenal permanente',
    fechaPublicacion: '2026-09-08',
    imagenes: ['https://images.unsplash.com/photo-1519708227418-c8fd9a32b7a2?auto=format&fit=crop&w=900&q=80'],
    descripcion: 'Pescado fresco de 1.0 a 1.4 kg por unidad, carne firme y blanca sin olor a barro.',
    certificaciones: ['AUNAP', 'Registro Sanitario']
  },
  {
    id: 'cos-023',
    titulo: 'Filete Fresco de Tilapia Negra sin Espinas',
    sector: 'acuicola',
    categoria: 'Filetes & Procesados',
    variedad: 'Oreochromis niloticus',
    cantidadDisponible: 10,
    unidad: 'Toneladas',
    precioUnitario: 24500,
    moneda: 'COP',
    departamento: 'Tolima',
    municipio: 'Prado (Represa de Prado)',
    vereda: 'Tomogó',
    coordenadas: [-74.9242, 3.7517],
    productor: {
      nombre: 'Acuícola Embalse de Prado',
      finca: 'Planta Hidrobiológica Prado',
      verificadoKYC: true,
      calificacion: 4.91,
      telefono: '+573167788990',
      whatsapp: '573167788990',
      experienciaAnos: 14
    },
    fechaCosechaEstimada: 'Despacho refrigerado diario',
    fechaPublicacion: '2026-09-10',
    imagenes: ['https://images.unsplash.com/photo-1534043464124-3be32fe000c9?auto=format&fit=crop&w=900&q=80'],
    descripcion: 'Filete grado sushi empacado al vacío con termoencogido, cadena de frío garantizada a 0-4°C.',
    certificaciones: ['INVIMA', 'BPA Acuícola AUNAP']
  },
  {
    id: 'cos-024',
    titulo: 'Alevinos de Tilapia Roja Revertida y Cachama',
    sector: 'acuicola',
    categoria: 'Semillas & Alevinaje',
    variedad: 'Tilapia Roja Monosexo 99%',
    cantidadDisponible: 50000,
    unidad: 'Cabezas',
    precioUnitario: 160,
    moneda: 'COP',
    departamento: 'Valle del Cauca',
    municipio: 'Guadalajara de Buga',
    vereda: 'Chambimbal',
    coordenadas: [-76.3014, 3.9009],
    productor: {
      nombre: 'Estación de Alevinaje del Valle',
      finca: 'Granja Piscícola La Rivera',
      verificadoKYC: true,
      calificacion: 4.97,
      telefono: '+573183344556',
      whatsapp: '573183344556',
      experienciaAnos: 22
    },
    fechaCosechaEstimada: 'Disponibilidad permanente con empaque con oxígeno',
    fechaPublicacion: '2026-09-09',
    imagenes: ['https://images.unsplash.com/photo-1544551763-46a013bb70d5?auto=format&fit=crop&w=900&q=80'],
    descripcion: 'Alevinos de 1.5 a 2.0 gramos con alta tasa de conversión alimenticia y supervivencia comprobada.',
    certificaciones: ['Registro de Productor de Semilla AUNAP / ICA']
  }
];

export const PRECIOS_MERCADO_DATA: PrecioMercado[] = [
  {
    id: 'pr-01',
    producto: 'Aguacate Hass Extra Exportación',
    sector: 'agricola',
    mercado: 'Corabastos Bogotá',
    departamento: 'Cundinamarca / Nacional',
    precioPromedio: 5400,
    precioMin: 4800,
    precioMax: 6000,
    unidad: 'Kg',
    variacion24h: 3.8,
    tendencia: 'alza',
    fechaActualizacion: 'Hoy 06:00 AM',
    fuente: 'SIPSA / DANE'
  },
  {
    id: 'pr-02',
    producto: 'Café Carga 125 Kg (Precio Base FNC)',
    sector: 'agricola',
    mercado: 'Comité Departamental FNC (Armenia/Manizales)',
    departamento: 'Eje Cafetero & Huila',
    precioPromedio: 2380000,
    precioMin: 2320000,
    precioMax: 2420000,
    unidad: 'Carga (125Kg)',
    variacion24h: 1.2,
    tendencia: 'alza',
    fechaActualizacion: 'Hoy 08:30 AM',
    fuente: 'FNC'
  },
  {
    id: 'pr-03',
    producto: 'Ganado Macho de Ceba 1a (En Pie)',
    sector: 'ganadero',
    mercado: 'Subasta Ganadera CC Subastas Montería',
    departamento: 'Córdoba',
    precioPromedio: 9650,
    precioMin: 9200,
    precioMax: 10100,
    unidad: 'Kg en pie',
    variacion24h: 0.5,
    tendencia: 'estable',
    fechaActualizacion: 'Ayer Tarde',
    fuente: 'FEDEGAN'
  },
  {
    id: 'pr-04',
    producto: 'Tilapia Roja Eviscerada',
    sector: 'acuicola',
    mercado: 'Plaza Mayorista de Medellín & Cavasa Cali',
    departamento: 'Antioquia / Valle',
    precioPromedio: 15200,
    precioMin: 14200,
    precioMax: 16500,
    unidad: 'Kg',
    variacion24h: -1.1,
    tendencia: 'baja',
    fechaActualizacion: 'Hoy 07:15 AM',
    fuente: 'FEDEACUA'
  },
  {
    id: 'pr-05',
    producto: 'Papa Criolla Lavada Primera',
    sector: 'agricola',
    mercado: 'Corabastos Bogotá',
    departamento: 'Boyacá / Cundinamarca',
    precioPromedio: 120000,
    precioMin: 110000,
    precioMax: 135000,
    unidad: 'Bulto (50Kg)',
    variacion24h: -4.5,
    tendencia: 'baja',
    fechaActualizacion: 'Hoy 05:45 AM',
    fuente: 'SIPSA / DANE'
  },
  {
    id: 'pr-06',
    producto: 'Plátano Hartón Verde de Primera',
    sector: 'agricola',
    mercado: 'Cavasa Cali',
    departamento: 'Valle del Cauca',
    precioPromedio: 3300,
    precioMin: 2900,
    precioMax: 3600,
    unidad: 'Kg',
    variacion24h: 2.1,
    tendencia: 'alza',
    fechaActualizacion: 'Hoy 06:00 AM',
    fuente: 'SIPSA / DANE'
  },
  {
    id: 'pr-07',
    producto: 'Trucha Arcoíris Entera Eviscerada',
    sector: 'acuicola',
    mercado: 'Centroabastos Bucaramanga',
    departamento: 'Santander / Boyacá',
    precioPromedio: 19500,
    precioMin: 18000,
    precioMax: 21000,
    unidad: 'Kg',
    variacion24h: 0.0,
    tendencia: 'estable',
    fechaActualizacion: 'Hoy 07:00 AM',
    fuente: 'FEDEACUA'
  },
  {
    id: 'pr-08',
    producto: 'Hembras Vientre F1 Certificadas',
    sector: 'ganadero',
    mercado: 'Subasta Sugaberrio (Pto. Berrío)',
    departamento: 'Antioquia / Magdalena Medio',
    precioPromedio: 4600000,
    precioMin: 4200000,
    precioMax: 5400000,
    unidad: 'Cabeza',
    variacion24h: 1.8,
    tendencia: 'alza',
    fechaActualizacion: 'Ayer',
    fuente: 'FEDEGAN'
  },
  {
    id: 'pr-09',
    producto: 'Cacao Grano Seco Fino y de Aroma',
    sector: 'agricola',
    mercado: 'Puntos Fedecacao Santander',
    departamento: 'Santander / Arauca',
    precioPromedio: 18200,
    precioMin: 17500,
    precioMax: 19400,
    unidad: 'Kg',
    variacion24h: 4.2,
    tendencia: 'alza',
    fechaActualizacion: 'Hoy 09:00 AM',
    fuente: 'AGROPACCIOLI Direct'
  },
  {
    id: 'pr-10',
    producto: 'Leche Cruda en Finca Grado A',
    sector: 'ganadero',
    mercado: 'Cuenca Norte de Antioquia / Sabana Bogotá',
    departamento: 'Antioquia / Cundinamarca',
    precioPromedio: 2450,
    precioMin: 2250,
    precioMax: 2650,
    unidad: 'Litro',
    variacion24h: 0.8,
    tendencia: 'estable',
    fechaActualizacion: 'Hoy 06:30 AM',
    fuente: 'FEDEGAN'
  },
  {
    id: 'pr-11',
    producto: 'Limón Tahití Extra',
    sector: 'agricola',
    mercado: 'Granabastos Barranquilla',
    departamento: 'Atlántico / Santander',
    precioPromedio: 4100,
    precioMin: 3600,
    precioMax: 4700,
    unidad: 'Kg',
    variacion24h: 1.5,
    tendencia: 'alza',
    fechaActualizacion: 'Hoy 06:15 AM',
    fuente: 'SIPSA / DANE'
  },
  {
    id: 'pr-12',
    producto: 'Camarón de Cultivo Marino Talla 30-40',
    sector: 'acuicola',
    mercado: 'Lonja Pesquera Cartagena / Buenaventura',
    departamento: 'Bolívar / Valle',
    precioPromedio: 27500,
    precioMin: 25000,
    precioMax: 29500,
    unidad: 'Kg',
    variacion24h: 0.0,
    tendencia: 'estable',
    fechaActualizacion: 'Hoy 08:00 AM',
    fuente: 'FEDEACUA'
  },
  {
    id: 'pr-13',
    producto: 'Arroz Paddy Verde Húmedo',
    sector: 'agricola',
    mercado: 'Molinos de Espinal / Villavicencio',
    departamento: 'Tolima / Meta',
    precioPromedio: 192000,
    precioMin: 184000,
    precioMax: 198000,
    unidad: 'Carga (125Kg)',
    variacion24h: -0.5,
    tendencia: 'baja',
    fechaActualizacion: 'Hoy 07:45 AM',
    fuente: 'SIPSA / DANE'
  },
  {
    id: 'pr-14',
    producto: 'Cebolla Junca Larga',
    sector: 'agricola',
    mercado: 'Corabastos Bogotá',
    departamento: 'Boyacá',
    precioPromedio: 55000,
    precioMin: 45000,
    precioMax: 62000,
    unidad: 'Rollo (40Kg)',
    variacion24h: -3.2,
    tendencia: 'baja',
    fechaActualizacion: 'Hoy 05:30 AM',
    fuente: 'SIPSA / DANE'
  }
];

export const ALMACENES_INSUMOS_DATA: AlmacenInsumos[] = [
  {
    id: 'alm-01',
    nombreComercial: 'AgroInsumos El Trebol & Nutrición Vegetal',
    razonSocial: 'Comercializadora Agropecuaria El Trebol S.A.S.',
    nit: '900.548.219-4',
    verificadoKYC: true,
    destacado: true,
    sectorEspecialidad: ['agricola'],
    departamento: 'Antioquia',
    municipio: 'Rionegro & Sonsón',
    direccion: 'Carrera 45 # 32-18 Parque Industrial del Oriente',
    telefono: '+57(4) 5612340',
    whatsapp: '573147890123',
    email: 'contacto@agroeltrebol.com.co',
    logo: 'https://images.unsplash.com/photo-1595246140625-573b715d11dc?auto=format&fit=crop&w=200&q=80',
    banner: 'https://images.unsplash.com/photo-1589923188900-85dae523342b?auto=format&fit=crop&w=1200&q=80',
    calificacion: 4.9,
    catalogoDestacado: [
      {
        nombre: 'Fertilizante Complejo 17-6-18-2 Bulto 50Kg',
        categoria: 'Fertilizantes Químicos',
        precio: 168000,
        unidad: 'Bulto',
        imagen: 'https://images.unsplash.com/photo-1628352081506-83c43123ed6d?auto=format&fit=crop&w=300&q=80',
        enStock: true
      },
      {
        nombre: 'Fungicida Sistémico Curativo Frasco 1L',
        categoria: 'Protección de Cultivos',
        precio: 95000,
        unidad: 'Litro',
        imagen: 'https://images.unsplash.com/photo-1587293852726-70cdb56c2866?auto=format&fit=crop&w=300&q=80',
        enStock: true
      },
      {
        nombre: 'Cal Dolomita Enmienda de Suelos 50Kg',
        categoria: 'Correctivos de Suelo',
        precio: 22000,
        unidad: 'Bulto',
        imagen: 'https://images.unsplash.com/photo-1585314062340-f1a5a7c9328d?auto=format&fit=crop&w=300&q=80',
        enStock: true
      }
    ],
    planesDisponibles: ['Vitrina Oro B2B', 'Despacho Rural Express']
  },
  {
    id: 'alm-02',
    nombreComercial: 'Ganavet & Nutrición Bovina de Colombia',
    razonSocial: 'Distribuciones Pecuarias del Sinú LTDA',
    nit: '812.334.908-1',
    verificadoKYC: true,
    destacado: true,
    sectorEspecialidad: ['ganadero'],
    departamento: 'Córdoba',
    municipio: 'Montería',
    direccion: 'Avenida Circunvalar # 14-88',
    telefono: '+57(4) 7824490',
    whatsapp: '573014561234',
    email: 'ventas@ganavetcolombia.com',
    logo: 'https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?auto=format&fit=crop&w=200&q=80',
    banner: 'https://images.unsplash.com/photo-1546445317-29f4545e9d53?auto=format&fit=crop&w=1200&q=80',
    calificacion: 4.8,
    catalogoDestacado: [
      {
        nombre: 'Sal Mineralizada al 8% Fósforo Ganadera 40Kg',
        categoria: 'Nutrición Bovina',
        precio: 89000,
        unidad: 'Saco',
        imagen: 'https://images.unsplash.com/photo-1563245372-f21724e3856d?auto=format&fit=crop&w=300&q=80',
        enStock: true
      },
      {
        nombre: 'Desparasitante Ivermectina 3.15% Frasco 500ml',
        categoria: 'Salud Animal & Fármacos',
        precio: 135000,
        unidad: 'Frasco',
        imagen: 'https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?auto=format&fit=crop&w=300&q=80',
        enStock: true
      }
    ],
    planesDisponibles: ['Vitrina Ganadera Premium', 'Asesoría Veterinaria Campo']
  },
  {
    id: 'alm-03',
    nombreComercial: 'Acuavida & Concentrados de los Llanos',
    razonSocial: 'Soluciones Acuícolas del Meta S.A.S.',
    nit: '901.782.112-9',
    verificadoKYC: true,
    destacado: true,
    sectorEspecialidad: ['acuicola'],
    departamento: 'Meta',
    municipio: 'Villavicencio & Restrepo',
    direccion: 'Zona Industrial Vía Catama Km 3',
    telefono: '+57(8) 6673322',
    whatsapp: '573176655443',
    email: 'comercial@acuavidallanos.com',
    logo: 'https://images.unsplash.com/photo-1570295999919-56ceb5ecca61?auto=format&fit=crop&w=200&q=80',
    banner: 'https://images.unsplash.com/photo-1534043464124-3be32fe000c9?auto=format&fit=crop&w=1200&q=80',
    calificacion: 4.95,
    catalogoDestacado: [
      {
        nombre: 'Concentrado Extruido Tilapia 32% Proteína 40Kg',
        categoria: 'Alimento Balanceado',
        precio: 112000,
        unidad: 'Bulto',
        imagen: 'https://images.unsplash.com/photo-1544551763-46a013bb70d5?auto=format&fit=crop&w=300&q=80',
        enStock: true
      },
      {
        nombre: 'Aireador de Paletas 2HP Trifásico para Estanques',
        categoria: 'Equipos & Oxigenación',
        precio: 2350000,
        unidad: 'Unidad',
        imagen: 'https://images.unsplash.com/photo-1581092160607-ee22621dd758?auto=format&fit=crop&w=300&q=80',
        enStock: true
      }
    ],
    planesDisponibles: ['Vitrina Acuícola Nacional', 'Crédito Directo Piscicultor']
  },
  {
    id: 'alm-04',
    nombreComercial: 'Agrovet del Huila & Asistencia Técnica',
    razonSocial: 'Insumos y Semillas de los Andes LTDA',
    nit: '891.100.432-6',
    verificadoKYC: true,
    destacado: true,
    sectorEspecialidad: ['agricola', 'ganadero'],
    departamento: 'Huila',
    municipio: 'Neiva & Pitalito',
    direccion: 'Avenida Pastrana Borrero # 20-50',
    telefono: '+57(8) 8721100',
    whatsapp: '573187766554',
    email: 'ventas@agrovetdelhuila.com',
    logo: 'https://images.unsplash.com/photo-1560250097-0b93528c311a?auto=format&fit=crop&w=200&q=80',
    banner: 'https://images.unsplash.com/photo-1500937386664-56d1dfef3854?auto=format&fit=crop&w=1200&q=80',
    calificacion: 4.88,
    catalogoDestacado: [
      {
        nombre: 'Fertilizante Cafetero Producción 17-6-18-2 Bulto 50Kg',
        categoria: 'Nutrición Café',
        precio: 162000,
        unidad: 'Bulto',
        imagen: 'https://images.unsplash.com/photo-1628352081506-83c43123ed6d?auto=format&fit=crop&w=300&q=80',
        enStock: true
      },
      {
        nombre: 'Vacuna Reproductiva Bovina Óctuple Frasco 50 Dosis',
        categoria: 'Biológicos Ganaderos',
        precio: 185000,
        unidad: 'Frasco',
        imagen: 'https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?auto=format&fit=crop&w=300&q=80',
        enStock: true
      }
    ],
    planesDisponibles: ['Vitrina Diamante Regional']
  },
  {
    id: 'alm-05',
    nombreComercial: 'Semillas & Agroquímicos del Valle (AgroValle)',
    razonSocial: 'Agroquímicos del Valle S.A.S.',
    nit: '890.312.450-8',
    verificadoKYC: true,
    destacado: true,
    sectorEspecialidad: ['agricola'],
    departamento: 'Valle del Cauca',
    municipio: 'Palmira & Tuluá',
    direccion: 'Carrera 28 # 45-12 Zona Agropecuaria',
    telefono: '+57(2) 2718899',
    whatsapp: '573169988776',
    email: 'contacto@agrovalle.com.co',
    logo: 'https://images.unsplash.com/photo-1586769852044-692d6e3703f0?auto=format&fit=crop&w=200&q=80',
    banner: 'https://images.unsplash.com/photo-1586201375761-83865001e31c?auto=format&fit=crop&w=1200&q=80',
    calificacion: 4.93,
    catalogoDestacado: [
      {
        nombre: 'Semilla Certificada de Maíz Híbrido Saco 60.000 semillas',
        categoria: 'Semillas Certificadas',
        precio: 480000,
        unidad: 'Saco',
        imagen: 'https://images.unsplash.com/photo-1585314062340-f1a5a7c9328d?auto=format&fit=crop&w=300&q=80',
        enStock: true
      },
      {
        nombre: 'Insecticida Biológico Bacillus Thuringiensis 1Kg',
        categoria: 'Control Biológico',
        precio: 72000,
        unidad: 'Kilo',
        imagen: 'https://images.unsplash.com/photo-1587293852726-70cdb56c2866?auto=format&fit=crop&w=300&q=80',
        enStock: true
      }
    ],
    planesDisponibles: ['Vitrina Platino Valle']
  },
  {
    id: 'alm-06',
    nombreComercial: 'Agroganadera del Cesar & Alambres San Isidro',
    razonSocial: 'Distribuciones Pecuarias del Cesar S.A.S.',
    nit: '900.223.119-1',
    verificadoKYC: true,
    destacado: true,
    sectorEspecialidad: ['ganadero'],
    departamento: 'Cesar',
    municipio: 'Valledupar & Aguachica',
    direccion: 'Calle 16B # 9-40',
    telefono: '+57(5) 5743322',
    whatsapp: '573005544332',
    email: 'ventas@agrocesar.com',
    logo: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=200&q=80',
    banner: 'https://images.unsplash.com/photo-1500595046743-cd271d694d30?auto=format&fit=crop&w=1200&q=80',
    calificacion: 4.87,
    catalogoDestacado: [
      {
        nombre: 'Rollo de Alambre de Púas Ganadero Calibre 14 (500 Metros)',
        categoria: 'Cercas & Infraestructura',
        precio: 215000,
        unidad: 'Rollo',
        imagen: 'https://images.unsplash.com/photo-1581092160607-ee22621dd758?auto=format&fit=crop&w=300&q=80',
        enStock: true
      },
      {
        nombre: 'Cerca Eléctrica Solar Inteligente con Impulsor 50 Km',
        categoria: 'Energía Solar Campo',
        precio: 890000,
        unidad: 'Equipo',
        imagen: 'https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?auto=format&fit=crop&w=300&q=80',
        enStock: true
      }
    ],
    planesDisponibles: ['Vitrina Caribe Ganadero']
  }
];

export const TRANSPORTISTAS_DATA: Transportista[] = [
  {
    id: 'tra-01',
    nombre: 'Transportes Rápidos del Campo (Don Jaime Morales)',
    tipoVehiculo: 'Turbo (4.5 Ton)',
    capacidadToneladas: 4.5,
    departamentoBase: 'Antioquia',
    municipioBase: 'Medellín / Rionegro',
    rutasFrecuentes: ['Oriente Antioqueño - Plaza Mayorista Medellín', 'Sonsón - Bogotá', 'Eje Cafetero'],
    verificadoKYC: true,
    calificacion: 4.95,
    viajesCompletados: 184,
    telefono: '+573128899001',
    whatsapp: '573128899001',
    tarifaBaseKm: 4200,
    disponibleInmediato: true,
    fotoVehiculo: 'https://images.unsplash.com/photo-1601584115197-04ecc0da31d7?auto=format&fit=crop&w=600&q=80'
  },
  {
    id: 'tra-02',
    nombre: 'Logística Frigorífica de los Andes (Carlos Bedoya)',
    tipoVehiculo: 'Termo King Refrigerado (10 Ton)',
    capacidadToneladas: 10.0,
    departamentoBase: 'Cundinamarca',
    municipioBase: 'Bogotá / Mosquera',
    rutasFrecuentes: ['Bogotá - Corabastos - Llanos Orientales', 'Boyacá - Bogotá', 'Tolima - Bogotá'],
    verificadoKYC: true,
    calificacion: 5.0,
    viajesCompletados: 310,
    telefono: '+573157766554',
    whatsapp: '573157766554',
    tarifaBaseKm: 6500,
    disponibleInmediato: true,
    fotoVehiculo: 'https://images.unsplash.com/photo-1586191582152-5c98692795f5?auto=format&fit=crop&w=600&q=80'
  },
  {
    id: 'tra-03',
    nombre: 'Camiones Ganaderos del Caribe (Jairo Fuentes)',
    tipoVehiculo: 'Doble Troque Ganadero (17 Ton)',
    capacidadToneladas: 17.0,
    departamentoBase: 'Córdoba',
    municipioBase: 'Montería / Caucasia',
    rutasFrecuentes: ['Montería - Medellín (Feria de Ganados)', 'Sucre - Bucaramanga', 'Llanos - Santander'],
    verificadoKYC: true,
    calificacion: 4.85,
    viajesCompletados: 142,
    telefono: '+573009988112',
    whatsapp: '573009988112',
    tarifaBaseKm: 5800,
    disponibleInmediato: true,
    fotoVehiculo: 'https://images.unsplash.com/photo-1519003722824-194d4455a60c?auto=format&fit=crop&w=600&q=80'
  },
  {
    id: 'tra-04',
    nombre: 'Carga Pesada & Tractomulas del Pacífico (Mauricio Henao)',
    tipoVehiculo: 'Tractomula (35 Ton)',
    capacidadToneladas: 35.0,
    departamentoBase: 'Valle del Cauca',
    municipioBase: 'Buenaventura / Buga',
    rutasFrecuentes: ['Puerto Buenaventura - Eje Cafetero - Bogotá', 'Valle - Medellín'],
    verificadoKYC: true,
    calificacion: 4.9,
    viajesCompletados: 420,
    telefono: '+573174455667',
    whatsapp: '573174455667',
    tarifaBaseKm: 8200,
    disponibleInmediato: true,
    fotoVehiculo: 'https://images.unsplash.com/photo-1501700493788-fa1a4fc9fe62?auto=format&fit=crop&w=600&q=80'
  },
  {
    id: 'tra-05',
    nombre: 'Fletes Boyacá & Páramo Express (Pedro Nel Albarracín)',
    tipoVehiculo: 'Sencillo Estacas (8.5 Ton)',
    capacidadToneladas: 8.5,
    departamentoBase: 'Boyacá',
    municipioBase: 'Tunja / Sogamoso / Aquitania',
    rutasFrecuentes: ['Aquitania - Corabastos Bogotá', 'Tunja - Bucaramanga', 'Boyacá - Casanare'],
    verificadoKYC: true,
    calificacion: 4.94,
    viajesCompletados: 260,
    telefono: '+573112233990',
    whatsapp: '573112233990',
    tarifaBaseKm: 4900,
    disponibleInmediato: true,
    fotoVehiculo: 'https://images.unsplash.com/photo-1601584115197-04ecc0da31d7?auto=format&fit=crop&w=600&q=80'
  },
  {
    id: 'tra-06',
    nombre: 'Transportes Acuícolas del Huila (Héctor Fabio Murcia)',
    tipoVehiculo: 'Furgón Isotérmico con Oxígeno (6 Ton)',
    capacidadToneladas: 6.0,
    departamentoBase: 'Huila',
    municipioBase: 'Neiva / Betania',
    rutasFrecuentes: ['Represa Betania - Bogotá', 'Neiva - Cali', 'Huila - Eje Cafetero'],
    verificadoKYC: true,
    calificacion: 4.98,
    viajesCompletados: 195,
    telefono: '+573158877665',
    whatsapp: '573158877665',
    tarifaBaseKm: 5400,
    disponibleInmediato: true,
    fotoVehiculo: 'https://images.unsplash.com/photo-1586191582152-5c98692795f5?auto=format&fit=crop&w=600&q=80'
  }
];

export const AGREMIACIONES_DATA: Agremiacion[] = [
  {
    id: 'agr-01',
    nombre: 'Federación Nacional de Cafeteros de Colombia',
    sigla: 'FNC',
    tipo: 'Gremio Nacional',
    cobertura: 'Nacional (600+ municipios)',
    afiliados: 540000,
    programasApoyo: ['Garantía de Compra', 'Asistencia Cenicafé', 'Renovación de Cafetales', 'Créditos Solidarios'],
    contacto: 'atencion@cafedecolombia.com',
    web: 'https://federaciondecafeteros.org',
    logo: 'https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?auto=format&fit=crop&w=200&q=80',
    descripcion: 'Representa legítimamente a las familias cafeteras de Colombia con asistencia técnica e investigación agronómica de vanguardia.'
  },
  {
    id: 'agr-02',
    nombre: 'Federación Colombiana de Ganaderos',
    sigla: 'FEDEGAN',
    tipo: 'Gremio Nacional',
    cobertura: 'Nacional',
    afiliados: 450000,
    programasApoyo: ['Ciclos de Vacunación Aftosa/Brucelosis', 'Ganadería Sostenible', 'Subastas Ganaderas', 'Trazabilidad Bovina'],
    contacto: 'contacto@fedegan.org.co',
    web: 'https://fedegan.org.co',
    logo: 'https://images.unsplash.com/photo-1546445317-29f4545e9d53?auto=format&fit=crop&w=200&q=80',
    descripcion: 'Lidera la modernización pecuaria, sostenibilidad ambiental y apertura de mercados internacionales.'
  },
  {
    id: 'agr-03',
    nombre: 'Federación Colombiana de Acuicultores',
    sigla: 'FEDEACUA',
    tipo: 'Gremio Nacional',
    cobertura: 'Meta, Huila, Antioquia, Tolima, Boyacá, Cundinamarca',
    afiliados: 12500,
    programasApoyo: ['Certificación Sanitaria', 'Cadenas de Exportación', 'Bioseguridad en Estanques y Represas'],
    contacto: 'presidencia@fedeacua.org',
    web: 'https://fedeacua.org',
    logo: 'https://images.unsplash.com/photo-1534043464124-3be32fe000c9?auto=format&fit=crop&w=200&q=80',
    descripcion: 'Impulsa el desarrollo acuícola nacional con sostenibilidad ecológica e inocuidad alimentaria.'
  },
  {
    id: 'agr-04',
    nombre: 'Fundación Agro Solidaria y Cooperativa Campesina',
    sigla: 'AGROSOLIDARIA',
    tipo: 'Fundación / ONG',
    cobertura: 'Boyacá, Nariño, Cauca, Santander',
    afiliados: 35000,
    programasApoyo: ['Comercio Justo Directo', 'Bancos Comunitarios de Semillas Nativas', 'Microcréditos para Mujeres Rurales'],
    contacto: 'red@agrosolidaria.org',
    logo: 'https://images.unsplash.com/photo-1595246140625-573b715d11dc?auto=format&fit=crop&w=200&q=80',
    descripcion: 'Red de apoyo campesino e indígena para el rescate de la soberanía alimentaria y comercialización sin intermediarios.'
  },
  {
    id: 'agr-05',
    nombre: 'Federación Nacional de Cultivadores de Palma de Aceite',
    sigla: 'FEDEPALMA',
    tipo: 'Gremio Nacional',
    cobertura: 'Cesar, Magdalena, Meta, Casanare, Santander',
    afiliados: 7000,
    programasApoyo: ['Palma Sostenible', 'Manejo de Pudrición del Cogollo', 'Crédito Verde'],
    contacto: 'fedepalma@fedepalma.org',
    web: 'https://fedepalma.org',
    logo: 'https://images.unsplash.com/photo-1500937386664-56d1dfef3854?auto=format&fit=crop&w=200&q=80',
    descripcion: 'Fomenta el cultivo de palma de aceite con altos estándares de conservación y formalización laboral.'
  },
  {
    id: 'agr-06',
    nombre: 'Asociación Hortofrutícola de Colombia',
    sigla: 'ASOHOFRUCOL',
    tipo: 'Gremio Nacional',
    cobertura: 'Nacional',
    afiliados: 180000,
    programasApoyo: ['Asistencia Integral Frutas y Hortalizas', 'Certificación GlobalGAP', 'Centros de Acopio'],
    contacto: 'contacto@asohofrucol.com.co',
    web: 'https://asohofrucol.com.co',
    logo: 'https://images.unsplash.com/photo-1523049673857-eb18f1d7b578?auto=format&fit=crop&w=200&q=80',
    descripcion: 'Administra el Fondo Nacional de Fomento Hortofrutícola para tecnificar a los productores de frutas y verduras.'
  }
];

export const NOTICIAS_DATA: NoticiaAgraria[] = [
  {
    id: 'not-001',
    titulo: 'Exportaciones de Aguacate Hass Colombiano Crecen un 24% Hacia Europa y EE.UU.',
    resumen: 'Antioquia y el Eje Cafetero lideran las ventas externas con estándares fitosanitarios de primera categoría.',
    contenido: 'Colombia sigue consolidándose como el principal proveedor emergente de aguacate Hass en los mercados internacionales gracias al cumplimiento de protocolos GlobalGAP e ICA.',
    categoria: 'Mercados',
    autor: 'Redacción Agropaccioli Economía',
    fecha: '10 de Septiembre, 2026',
    imagen: 'https://images.unsplash.com/photo-1523049673857-eb18f1d7b578?auto=format&fit=crop&w=1000&q=80',
    destacada: true,
    fuenteOficial: 'Ministerio de Agricultura / ProColombia'
  },
  {
    id: 'not-002',
    titulo: 'Alerta Fitosanitaria por Clima: Manejo Preventivo de Roya y Broca del Café',
    resumen: 'El ICA y Cenicafé emiten boletín técnico ante las variaciones de precipitaciones en el Huila y Tolima.',
    contenido: 'Ante las recientes precipitaciones intercaladas con alta radiación solar, los comités departamentales instan a intensificar los monitoreos sanitarios semanales.',
    categoria: 'Alertas Fitosanitarias',
    autor: 'Ing. Agrónomo Rodrigo Morales',
    fecha: '09 de Septiembre, 2026',
    imagen: 'https://images.unsplash.com/photo-1442512595331-e89e73853f31?auto=format&fit=crop&w=1000&q=80',
    destacada: false,
    fuenteOficial: 'Instituto Colombiano Agropecuario (ICA)'
  },
  {
    id: 'not-003',
    titulo: 'Lanzamiento de la Línea Especial de Crédito LEC con Tasa Subsidiada para Jóvenes Rurales',
    resumen: 'Finagro y Banco Agrario disponen de una bolsa de $450.000 millones para tecnificación y riego.',
    contenido: 'Con tasas desde el IBR - 3% EA, los nuevos créditos permitirán la instalación de paneles solares en salas de ordeño y estanques acuícolas con recirculación.',
    categoria: 'Políticas & Créditos',
    autor: 'Mesa Técnica Financiera',
    fecha: '08 de Septiembre, 2026',
    imagen: 'https://images.unsplash.com/photo-1595246140625-573b715d11dc?auto=format&fit=crop&w=1000&q=80',
    destacada: false,
    fuenteOficial: 'FINAGRO / MinAgricultura'
  },
  {
    id: 'not-004',
    titulo: 'Apertura de Nuevos Mercados en el Caribe para Carne Bovina Colombiana con Sello Verde',
    resumen: 'FEDEGAN y MinComercio anuncian protocolo sanitario para cortes finos producidos en sistemas silvopastoriles.',
    contenido: 'Los frigoríficos certificados de Córdoba, Magdalena Medio y Santander comenzarán despachos marítimos directos a las Antillas y Centroamérica.',
    categoria: 'Ganadería & Acuicultura',
    autor: 'Comité Técnico Ganadero',
    fecha: '07 de Septiembre, 2026',
    imagen: 'https://images.unsplash.com/photo-1546445317-29f4545e9d53?auto=format&fit=crop&w=1000&q=80',
    destacada: false,
    fuenteOficial: 'INVIMA / FEDEGAN'
  }
];

export const TRM_DATA = {
  dolarCOP: 4185.50,
  euroCOP: 4530.20,
  variacionDolar: -12.30,
  fecha: '10 de Septiembre, 2026'
};

// ==================== BOLSA DE EMPLEO RURAL & AGROPECUARIO ====================
export const EMPLEOS_DATA: EmpleoItem[] = [
  {
    id: 'emp-001',
    titulo: 'Administrador de Finca Cafetera Especial',
    empresaOFinca: 'Hacienda El Cafetal & Café Los Andes',
    sector: 'agricola',
    cargo: 'Administrador General de Predio',
    tipoContrato: 'mensual',
    departamento: 'Huila',
    municipio: 'Pitalito',
    vereda: 'Criollo',
    salarioTexto: '$2.800.000 COP / mes + Bonos de Cosecha',
    salarioNumerico: 2800000,
    incluyeVivienda: true,
    incluyeAlimentacion: true,
    vacantesDisponibles: 1,
    experienciaRequerida: 'Mínimo 3 años administrando fincas cafeteras tecnificadas.',
    descripcion: 'Buscamos persona o pareja con experiencia comprobada en manejo de personal de recolección, beneficio ecológico por vía húmeda, curvas de secado solar y control de inventarios de fertilizantes.',
    requisitos: [
      'Conocimiento en procesos de beneficio y tostión de cafés especiales',
      'Manejo de nómina de recolectores (hasta 40 personas en cosecha)',
      'Buenas Prácticas Agrícolas (BPA ICA)',
      'Referencias laborales verificables'
    ],
    beneficios: [
      'Casa independiente amoblada con servicios incluidos',
      'Alimentación en la finca',
      'Seguridad social integral (Salud, Pensión, ARL Riesgo IV)',
      'Bonificación trimestral por rendimiento en tasa limpia'
    ],
    contactoNombre: 'Don Carlos Eduardo Ramírez (Propietario)',
    contactoTelefono: '+573138901234',
    contactoWhatsapp: '573138901234',
    fechaPublicacion: '18 de Septiembre, 2026',
    verificadoKYC: true,
    urgente: true
  },
  {
    id: 'emp-002',
    titulo: 'Mayordomo Ganadero y Encargado de Lotes de Ceba',
    empresaOFinca: 'Ganadería La Pradera S.A.S.',
    sector: 'ganadero',
    cargo: 'Mayordomo Ganadero Residente',
    tipoContrato: 'mensual',
    departamento: 'Córdoba',
    municipio: 'Montería',
    vereda: 'El Sabanal',
    salarioTexto: '$2.200.000 COP / mes + Prestaciones',
    salarioNumerico: 2200000,
    incluyeVivienda: true,
    incluyeAlimentacion: false,
    vacantesDisponibles: 1,
    experienciaRequerida: '2 años en manejo de ganado Brahman y pastoreo rotacional Voisin.',
    descripcion: 'Se requiere mayordomo de confianza para coordinar el manejo de 250 cabezas de ganado de ceba y cría, pesaje mensual, planes de vacunación oficial ICA y mantenimiento de cercas eléctricas.',
    requisitos: [
      'Experiencia en inseminación artificial o monta controlada',
      'Manejo de registros de ganancia de peso diaria',
      'Mantenimiento básico de guadaña y motobomba'
    ],
    beneficios: [
      'Vivienda familiar en material con energía solar y agua potable',
      'Espacio para huerta casera y animales menores',
      'Contrato a término indefinido con todas las prestaciones'
    ],
    contactoNombre: 'Dr. Álvaro Restrepo (Administración)',
    contactoTelefono: '+573105556677',
    contactoWhatsapp: '573105556677',
    fechaPublicacion: '19 de Septiembre, 2026',
    verificadoKYC: true,
    urgente: false
  },
  {
    id: 'emp-003',
    titulo: 'Operario Tractorista y Maquinaria Agrícola',
    empresaOFinca: 'Agroinsumos & Siembras del Llano',
    sector: 'agricola',
    cargo: 'Operario de Tractor y Cosechadora',
    tipoContrato: 'mensual',
    departamento: 'Meta',
    municipio: 'Villavicencio',
    vereda: 'Apiay',
    salarioTexto: '$2.400.000 COP / mes + Horas Extras',
    salarioNumerico: 2400000,
    incluyeVivienda: true,
    incluyeAlimentacion: true,
    vacantesDisponibles: 2,
    experienciaRequerida: 'Mínimo 2 años operando tractores agrícolas New Holland / John Deere.',
    descripcion: 'Operación de maquinaria pesada para preparación de tierras de arroz y maíz, arado, rastrillada, siembra mecanizada y fumigación con aguilón.',
    requisitos: [
      'Licencia de conducción C2 vigente',
      'Conocimientos en mecánica diésel preventiva y cambio de implementos',
      'Disponibilidad para turnos en temporada de preparación'
    ],
    beneficios: [
      'Campamento con aire acondicionado y alimentación completa',
      'Pago oportuno quincenal con recargos',
      'Capacitación en agricultura de precisión con GPS'
    ],
    contactoNombre: 'Ing. Sandra Milena Torres',
    contactoTelefono: '+573142223344',
    contactoWhatsapp: '573142223344',
    fechaPublicacion: '20 de Septiembre, 2026',
    verificadoKYC: true,
    urgente: true
  },
  {
    id: 'emp-004',
    titulo: 'Técnico Piscícola en Cultivo de Tilapia Roja y Trucha',
    empresaOFinca: 'Piscícola San Jerónimo & AcuaBetania',
    sector: 'acuicola',
    cargo: 'Técnico de Producción Acuícola',
    tipoContrato: 'mensual',
    departamento: 'Huila',
    municipio: 'Yaguará',
    vereda: 'Embalse de Betania',
    salarioTexto: '$2.300.000 COP / mes + Bonos de Crecimiento',
    salarioNumerico: 2300000,
    incluyeVivienda: true,
    incluyeAlimentacion: false,
    vacantesDisponibles: 2,
    experienciaRequerida: 'Técnico o tecnólogo SENA en Acuicultura o 3 años de experiencia en jaulas flotantes.',
    descripcion: 'Monitoreo de parámetros físico-químicos del agua (oxígeno disuelto, pH, amonio, temperatura), tablas de alimentación por biomasa, biometrías semanales y despachos a plantas de eviscerado.',
    requisitos: [
      'Saber nadar y manejo básico de embarcación con motor fuera de borda',
      'Manejo de oxímetros digitales y sondas multiparamétricas',
      'Conocimiento en normas de inocuidad piscícola INVIMA'
    ],
    beneficios: [
      'Habitación privada en campamento flotante / base terrestre',
      'Dotación completa y elementos de protección náutica',
      'Plan de bonos por factor de conversión alimenticia (FCA)'
    ],
    contactoNombre: 'Biol. Javier Ocampo',
    contactoTelefono: '+573129998877',
    contactoWhatsapp: '573129998877',
    fechaPublicacion: '17 de Septiembre, 2026',
    verificadoKYC: true,
    urgente: false
  },
  {
    id: 'emp-005',
    titulo: 'Cuadrilla de Recolectores de Aguacate Hass de Exportación',
    empresaOFinca: 'Finca La Esmeralda GlobalGAP',
    sector: 'agricola',
    cargo: 'Recolectores Especializados de Fruta',
    tipoContrato: 'jornal',
    departamento: 'Antioquia',
    municipio: 'Sonsón',
    vereda: 'La Soledad',
    salarioTexto: '$75.000 COP / Jornal Diario + Incentivos',
    salarioNumerico: 75000,
    incluyeVivienda: false,
    incluyeAlimentacion: true,
    vacantesDisponibles: 15,
    experienciaRequerida: 'Cosecha con tijera podadora y canastillas sin golpear el fruto.',
    descripcion: 'Temporada de cosecha principal de aguacate Hass. Corte con pedúnculo adecuado, selección por calibre y cargue ordenado a camiones refrigerados.',
    requisitos: [
      'Manejo cuidadoso de la fruta de exportación',
      'Disponibilidad para iniciar labores a las 6:00 AM',
      'Documento de identidad al día'
    ],
    beneficios: [
      'Pago semanal todos los sábados',
      'Refrigerio matutino y almuerzo en campo incluido',
      'Ruta de transporte desde el parque principal de Sonsón'
    ],
    contactoNombre: 'Don Hernando Gómez',
    contactoTelefono: '+573114567890',
    contactoWhatsapp: '573114567890',
    fechaPublicacion: '21 de Septiembre, 2026',
    verificadoKYC: true,
    urgente: true
  },
  {
    id: 'emp-006',
    titulo: 'Ingeniero Agrónomo - Asistente Técnico en Cítricos y Aguacate',
    empresaOFinca: 'Consorcio Frutícola del Valle',
    sector: 'profesional',
    cargo: 'Agrónomo de Campo / Fitosanitarista',
    tipoContrato: 'prestacion_servicios',
    departamento: 'Valle del Cauca',
    municipio: 'Roldanillo',
    vereda: 'La Tulia',
    salarioTexto: '$3.800.000 COP / mes + Rodamiento',
    salarioNumerico: 3800000,
    incluyeVivienda: false,
    incluyeAlimentacion: false,
    vacantesDisponibles: 1,
    experienciaRequerida: 'Profesional en Agronomía con tarjeta profesional y 2 años de experiencia.',
    descripcion: 'Diseño y supervisión de planes de fertilización edáfica y foliar, monitoreo de HLB en cítricos y trips en aguacate, formulación de bioinsumos y auditoría para recertificación Rainforest Alliance.',
    requisitos: [
      'Tarjeta profesional vigente',
      'Vehículo o motocicleta propia (se cubre auxilio de rodamiento)',
      'Manejo de software GIS o levantamientos satelitales'
    ],
    beneficios: [
      'Horarios flexibles con visitas programadas',
      'Auxilio de transporte y combustible ($600.000 COP adicionales)',
      'Excelente ambiente en empresa de exportación'
    ],
    contactoNombre: 'Dra. Marcela Cardona',
    contactoTelefono: '+573157778899',
    contactoWhatsapp: '573157778899',
    fechaPublicacion: '16 de Septiembre, 2026',
    verificadoKYC: true,
    urgente: false
  },
  {
    id: 'emp-007',
    titulo: 'Encargado de Invernadero Hidropónico (Tomate & Pimentón)',
    empresaOFinca: 'AgroEco Boyacá Cultivos Protegidos',
    sector: 'agricola',
    cargo: 'Operario Encargado de Invernadero',
    tipoContrato: 'mensual',
    departamento: 'Boyacá',
    municipio: 'Villa de Leyva',
    vereda: 'Roba',
    salarioTexto: '$2.000.000 COP / mes + Vivienda',
    salarioNumerico: 2000000,
    incluyeVivienda: true,
    incluyeAlimentacion: false,
    vacantesDisponibles: 1,
    experienciaRequerida: '1 año en labores de tutorado, poda, deschuponado y cosecha en invernaderos.',
    descripcion: 'Manejo diario de invernadero de 5.000 m2 con fertirriego computarizado. Limpieza, control biológico de plagas con extractos botánicos y empaque de tomate chonto gourmet.',
    requisitos: [
      'Puntualidad y atención al detalle',
      'Conocimiento en lectura de conductividad eléctrica y pH en sustrato de cascarilla'
    ],
    beneficios: [
      'Alojamiento campestre en la finca con todos los servicios',
      'Contrato laboral directo con prestaciones de ley',
      'Bonificación por porcentaje de fruta tipo primera'
    ],
    contactoNombre: 'Ing. Pedro Pablo Cárdenas',
    contactoTelefono: '+573164445566',
    contactoWhatsapp: '573164445566',
    fechaPublicacion: '19 de Septiembre, 2026',
    verificadoKYC: true,
    urgente: false
  },
  {
    id: 'emp-008',
    titulo: 'Médico Veterinario Zootecnista para Hato Lechero Especializado',
    empresaOFinca: 'Hacienda La Alquería del Norte',
    sector: 'profesional',
    cargo: 'Veterinario Residente de Hato',
    tipoContrato: 'mensual',
    departamento: 'Antioquia',
    municipio: 'Santa Rosa de Osos',
    vereda: 'Llanos de Cuivá',
    salarioTexto: '$4.200.000 COP / mes + Habitación Suite',
    salarioNumerico: 4200000,
    incluyeVivienda: true,
    incluyeAlimentacion: true,
    vacantesDisponibles: 1,
    experienciaRequerida: 'Mínimo 3 años en reproducción bovina, ecografía y sanidad en vacas Holstein.',
    descripcion: 'Dirección médica y reproductiva de lechería de 180 vacas en ordeño mecánico con tanque frío. Transferencia de embriones, control de mastitis, balanceo de raciones TMR y salud de terneraje.',
    requisitos: [
      'Título profesional y matrícula profesional COMVEZCOL',
      'Experiencia demostrable en ecografía reproductiva',
      'Manejo de software ganadero (ej. TaurusWeb o Ganadero SG)'
    ],
    beneficios: [
      'Habitación privada amoblada en la casona principal con alimentación',
      'Contrato a término indefinido con prima extralegal anual',
      'Laboratorio clínico veterinario equipado en la finca'
    ],
    contactoNombre: 'Sr. Jorge Mario Montoya',
    contactoTelefono: '+573181112233',
    contactoWhatsapp: '573181112233',
    fechaPublicacion: '15 de Septiembre, 2026',
    verificadoKYC: true,
    urgente: true
  }
];
